"""added ID

Revision ID: 2231e434e56a
Revises: ae9ea926ad15
Create Date: 2025-07-06 13:29:17.203122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2231e434e56a'
down_revision: Union[str, None] = 'ae9ea926ad15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('knowledge_base_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'knowledge_base_id')
    # ### end Alembic commands ###
