"""update on calendly model

Revision ID: 225824732cd0
Revises: 04f5dc7a8935
Create Date: 2025-07-31 19:33:50.088923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225824732cd0'
down_revision: Union[str, None] = '04f5dc7a8935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('external_system', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('calendly_event_uri', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('calendly_invitee_uri', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('calendly_access_token', sa.String(length=500), nullable=True))
    op.add_column('clinics', sa.Column('calendly_refresh_token', sa.String(length=500), nullable=True))
    op.add_column('clinics', sa.Column('calendly_user_uri', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('calendly_organization_uri', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('calendly_webhook_signing_key', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('calendly_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clinics', sa.Column('calendly_sync_enabled', sa.Boolean(), nullable=True))
    op.alter_column('clinics', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinics', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('clinics', 'calendly_sync_enabled')
    op.drop_column('clinics', 'calendly_connected_at')
    op.drop_column('clinics', 'calendly_webhook_signing_key')
    op.drop_column('clinics', 'calendly_organization_uri')
    op.drop_column('clinics', 'calendly_user_uri')
    op.drop_column('clinics', 'calendly_refresh_token')
    op.drop_column('clinics', 'calendly_access_token')
    op.drop_column('appointments', 'calendly_invitee_uri')
    op.drop_column('appointments', 'calendly_event_uri')
    op.drop_column('appointments', 'external_system')
    op.drop_column('appointments', 'external_id')
    # ### end Alembic commands ###
