"""extend knowledge_base_id column to text

Revision ID: a847f83813cf
Revises: 225824732cd0
Create Date: 2025-08-05 10:38:18.823789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a847f83813cf'
down_revision: Union[str, None] = '225824732cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('conversation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_calls_conversation_id'), 'calls', ['conversation_id'], unique=True)
    op.alter_column('clinics', 'knowledge_base_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinics', 'knowledge_base_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_calls_conversation_id'), table_name='calls')
    op.drop_column('calls', 'conversation_id')
    # ### end Alembic commands ###
