"""added clinic twilio and elevenlabs integrations

Revision ID: ae9ea926ad15
Revises: fb857fd5cc8b
Create Date: 2025-07-05 19:42:01.750548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9ea926ad15'
down_revision: Union[str, None] = 'fb857fd5cc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('twilio_phone_number', sa.String(length=20), nullable=True))
    op.add_column('clinics', sa.Column('elevenlabs_agent_id', sa.String(length=100), nullable=True))
    op.add_column('clinics', sa.Column('elevenlabs_agent_name', sa.String(length=255), nullable=True))
    op.add_column('clinics', sa.Column('setup_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'setup_results')
    op.drop_column('clinics', 'elevenlabs_agent_name')
    op.drop_column('clinics', 'elevenlabs_agent_id')
    op.drop_column('clinics', 'twilio_phone_number')
    # ### end Alembic commands ###
