"""add hash to staff and clinic table

Revision ID: fb857fd5cc8b
Revises: 3cb6fdb2ddc1
Create Date: 2025-06-05 11:39:52.138236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb857fd5cc8b'
down_revision: Union[str, None] = '3cb6fdb2ddc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('staff', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('clinics', sa.Column('email_verification_code', sa.String(length=10), nullable=True))
    op.add_column('clinics', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password_hash')
    op.drop_column('clinics', 'password_hash')
    op.drop_column('clinics', 'email_verification_code')
    op.drop_column('clinics', 'email_verified')
    # ### end Alembic commands ###
